from .ClickIntervalFrame import CustomClickIntervalFrame
from .ClickOptionFrame import CustomClickOptionFrame
from .ClickRepeatFrame import CustomClickRepeatFrame
from .CursorPositionFrame import CustomCursorPositionFrame
from .ActionFrame import CustomActionFrame
